return {
  {
    "nvim-treesitter/nvim-treesitter",
    run = ":TSUpdate",
    config = function()
      require("config.plugin.treesitter.setup")
      vim.api.nvim_exec_autocmds("FileType", {
        pattern = vim.bo.filetype,
        modeline = false,
      }) -- SEE: https://github.com/neovim/neovim/issues/23368
    end,
    ft = {
      "astro",
      "bash",
      "bib",
      "blade",
      "c",
      "cmake",
      "cpp",
      "cs",
      "css",
      "dart",
      "diff",
      "dockerfile",
      "dosini",
      "fish",
      "fennel",
      "gitcommit",
      "gitconfig",
      "gitignore",
      "gitrebase",
      "go",
      "gomod",
      "gosum",
      "graphql",
      "help",
      "html",
      "htmldjango",
      "java",
      "javascript",
      "javascriptreact",
      "json",
      "jsonc",
      "kotlin",
      "lua",
      "make",
      "markdown",
      "meson",
      "ninja",
      "php",
      "plantuml",
      "python",
      "query",
      "rust",
      "sbt",
      "scala",
      "scfg",
      "scheme",
      "scss",
      "sh",
      "sshconfig",
      "sql",
      "svelte",
      "TelescopePrompt",
      "tex",
      "tmux",
      "toml",
      "typescript",
      "typescriptreact",
      "vim",
      "vlang",
      "vue",
      "yaml",
      "zig",
    },
    event = { "User TelescopePreviewerLoaded" },
  },
  {
    "nvim-treesitter/nvim-treesitter-textobjects",
    after = "nvim-treesitter",
  },
  { "theHamsta/nvim-treesitter-pairs", after = "nvim-treesitter" },
}
