return {
  "phaazon/hop.nvim",
  config = function()
    require("plugin.hop.config")
    require("plugin.hop.keymap")
  end,
  cmd = {
    "HopWord",
    "HopWordAC",
    "HopWordBC",
    "HopWordMW",
    "HopWordCurrentLineAC",
    "HopWordCurrentLineBC",
    "HopLine",
    "HopLineAC",
    "HopLineBC",
    "HopLineMW",
    "HopLineStart",
    "HopLineStartAC",
    "HopLineStartBC",
    "HopLineStartMW",
    "HopChar1",
    "HopChar1AC",
    "HopChar1BC",
    "HopChar1MW",
    "HopChar1CurrentLineAC",
    "HopChar1CurrentLineBC",
    "HopChar2",
    "HopChar2AC",
    "HopChar2BC",
    "HopChar2MW",
    "HopChar2CurrentLineAC",
    "HopChar2CurrentLineBC",
    "HopPattern",
    "HopPatternAC",
    "HopPatternBC",
    "HopPatternMW",
    "HopPatternCurrentLineAC",
    "HopPatternCurrentLineBC",
  },
  keys = { "f", "F", "<M-f>" },
}
