return {
  Text = { text = "Text", icon = "" },
  Method = { text = "Method", icon = "" },
  Function = { text = "Function", icon = "" },
  Constructor = { text = "Constructor", icon = "" },
  Field = { text = "Field", icon = "ﰠ" },
  Variable = { text = "Variable", icon = "" },
  Class = { text = "Class", icon = "" },
  Interface = { text = "Interface", icon = "ﰮ" },
  Module = { text = "Module", icon = { "" } },
  Property = { text = "Property", icon = "襁" },
  Unit = { text = "Unit", icon = "塞" },
  Value = { text = "Value", icon = "" },
  Enum = { text = "Enum", icon = "練" },
  Keyword = { text = "Keyword", icon = "" },
  Snippet = { text = "Snippet", icon = "" },
  Color = { text = "Color", icon = "" },
  File = { text = "File", icon = "" },
  Reference = { text = "Reference", icon = "" },
  Folder = { text = "Folder", icon = "" },
  EnumMember = { text = "EnumMember", icon = "" },
  Constant = { text = "Constant", icon = "" },
  Struct = { text = "Struct", icon = "פּ" },
  Event = { text = "Event", icon = "ﯓ" },
  Operator = { text = "Operator", icon = "" },
  TypeParameter = { text = "TypeParameter", icon = "" },
}
