-- local g = vim.g
-- g["sandwich#recipes"] = vim.fn.deepcopy(g["sandwich#default_recipes"])
-- g["sandwich#recipes"] =
--     g["sandwich#recipes"],
--     { buns = {'{ ', ' }'}, nesting= 1, match_syntax= 1, kind= {'add', 'replace'}, action= {'add'}, input= {'{'}},
--     { buns = {'[ ', ' ]'}, nesting= 1, match_syntax= 1, kind= {'add', 'replace'}, action= {'add'}, input= {'['}},
--     { buns = {'( ', ' )'}, nesting= 1, match_syntax= 1, kind= {'add', 'replace'}, action= {'add'}, input= {'('}},
--     { buns = {[[{\s*]], [[\s*}]]},   nesting= 1, regex= 1, match_syntax= 1, kind= {'delete', 'replace', 'textobj'}, action= {'delete'}, input= {'{'}},
--     { buns = {[[\[\s*]], [[\s*\]\]]}, nesting= 1, regex= 1, match_syntax= 1, kind= {'delete', 'replace', 'textobj'}, action= {'delete'}, input= {'['}},
--     { buns = {[[(\s*]], [[\s*)]]},   nesting= 1, regex= 1, match_syntax= 1, kind= {'delete', 'replace', 'textobj'}, action= {'delete'}, input= {'('}}

-- local var = some random string
