local global = vim.g

global.mapleader = " "
global.python3_host_prog = "$HOME/.local/lib/pyenvs/neovim/bin/python"
global.loaded_spec = 1
global.loaded_gzip = 1
global.loaded_tar = 1
global.loaded_tarPlugin = 1
global.loaded_zip = 1
global.loaded_zipPlugin = 1
global.loaded_getscript = 1
global.loaded_getscriptPlugin = 1
global.loaded_vimball = 1
global.loaded_vimballPlugin = 1
global.loaded_matchit = 1
global.loaded_matchparen = 1
global.loaded_2html_plugin = 1
global.loaded_logiPat = 1
global.loaded_rrhelper = 1
global.loaded_netrw = 1
global.loaded_netrwPlugin = 1
global.loaded_netrwSettings = 1
global.loaded_netrwFileHandlers = 1
